# Generated by Django 5.2.14 on 2026-05-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='follow',
            new_name='users_follo_followe_4166a2_idx',
            old_name='users_follo_followe_2f822a_idx',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='users_follo_followi_e01def_idx',
            old_name='users_follo_followi_a82948_idx',
        ),
    ]
