# Generated by Django 5.2.15 on 2026-06-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(
                choices=[
                    ('cafe', 'Cafe'),
                    ('park', 'Park'),
                    ('mountain', 'Mountain'),
                    ('workspace', 'Workspace'),
                    ('gaming', 'Gaming place'),
                    ('hidden_spot', 'Hidden spot'),
                    ('tourist', 'Tourist place'),
                    ('restaurant', 'Restaurant'),
                    ('museum', 'Museum'),
                    ('other', 'Other'),
                ],
                default='other',
                max_length=32,
            ),
        ),
    ]
