# Generated by Django 5.2.15 on 2026-06-23 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/%Y/%m/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post')),
            ],
            options={
                'ordering': ('order', 'id'),
                'indexes': [models.Index(fields=['post', 'order'], name='posts_image_post_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'order'), name='unique_post_image_order'), models.CheckConstraint(condition=models.Q(('order__gte', 0), ('order__lte', 3)), name='post_image_order_range')],
            },
        ),
    ]
